### ISSUE TITLE
Differenza rispetto alla repository firmware_stock_5?

### ISSUE THREAD

**Issue by ghost** [flyingbear-club-ita/mks-robin-nano-1.x#1]
Ho provato a installare il firmware per la mia Ghost 5 anche dall'altra repository. L'interfaccia è molto più professionale ma necessità di configurazione da 0. Questa è una versione firmware già adattata alla Ghost 5 quindi? Mentre l'altra è per le schede Robin nano in generale?

**Comment by poty87** [comment]
è possibile avere il marlin non compilato settato correttamente per la ghost 5? vorrei smanettarci sopra e magari contribuire visto che sono un programmatore ma avete pubblicato solo il firmware compilato che, per quanto già funzioni, mi piacerebbe implementarci il linear advance al firmware.
