### ISSUE TITLE
Problema Wifi Module

### ISSUE THREAD

**Issue by LucaPetrucci** [flyingbear-club-ita/mks-robin-nano-1.x#2]
Dopo aver installato questo firmware su Ghost 5 Stock (STM32F103 - 2x TMC2208 - 2x A4988s) il modulo wifi non funziona, rimane bloccato sulla scritta "The wifi module is being configured please wait a moment..." 
Suggerimenti su come potrei risolvere? In alternativa sarebbe possibile avere il source code o i file Configuration.h e Configuration_adv.h con le configurazioni per la Ghost 5 Stock da usare per ricompilare il Marlin 2 da zero?

**Comment by Clayblock** [comment]
Ciao Luca, 
nella versione MARLIN_UI purtroppo si perde la compatibilitá con il wifi.
Purtroppo all'epoca del tuo commento usando la LVGL_UI si aveva un bug di layer shifting, che al momento sembra essere stato fixato.
Spero di esserti stato d'aiuto, anche se rispondo dopo piu di un anno e mezzo.
Grazie.
